### ISSUE TITLE
How to stop htmlhint from linting markdown files? 

### ISSUE THREAD

**Issue by jtheletter** [mmaday/SublimeLinter-contrib-htmlhint#19]
Regarding the `htmlhint` plugin for Sublime, I'm seeing flags raised in `readme.md` files, such as this: 

```
htmlhint: error
doctype-first - Doctype must be declared first.
```

And:

```
htmlhint: error
spec-char-escape - Special characters must be escaped : [ > ].
```

htmlhint is properly linting `*.html` files. It's not mis-linting other files, such as `*.css` and `*.js`. 

Why is it linting markdown files?

If I'm required to exclude them, how do I? Should I add a file to my machine's home directory, such as `~/.htmlhint`? What should it say? The following doesn't work:

```
{
    "exclude": ["**/*.md"]
}
```

* macOS Catalina Version 10.15.4 (19E287)
* Sublime Text Version 3.2.2, Build 3211
* htmlhint --version 0.10.1

**Comment by Shinigami92** [comment]
https://github.com/htmlhint/SublimeLinter-contrib-htmlhint/blob/4fdda9e7e25976ed2f6222f2074d7422de030e43/linter.py#L26

This line is taking `stdin`
It doesn't check if it's a `html` file, it takes everything thats currently in scope

**Comment by kaste** [comment]
Just seeing this.  You can try a different selector, e.g.

```
  "htmlhint": {
     "selector": "text.html - text.html.markdown"
  }
```

http://www.sublimelinter.com/en/stable/linter_settings.html#selector

This could be a good default as well.  

Otherwise, the name of the key to "exclude" is "excludes" in SublimeLinter.  http://www.sublimelinter.com/en/stable/linter_settings.html#excludes

```
     "excludes": "*.md"
```

**Comment by jtheletter** [comment]
If I create a file `~/.htmlhintrc` as:

```
{
    "excludes": "*.md"
}
```

HtmlHint stops working. Why might that be?

Where might I put such a `selector` config for global usage?

**Comment by kaste** [comment]
Both "selector" and "excludes" are SublimeLinter settings.  So you set them within Sublime Text.  Globally, using the Command Palette `ctrl+shit+p`, then type `SLS` and look for `SublimeLinter Settings`.  Can also be used per project, Command Palette `Edit Project`.

**Comment by jtheletter** [comment]
Thank you. When I change the file at `~/Library/Application Support/Sublime Text 3/Packages/User/SublimeLinter.sublime-settings` to include the following config, the linter no longer triggers on MD files, and it continues to work on HTML files. Issue solved. 

```
{
    "linters": {
        "htmlhint": {
             "excludes": "*.md"
        }
    }
}
```
