### ISSUE TITLE
Obvious question?

### ISSUE THREAD

**Issue by nmaxcom** [mmaday/SublimeLinter-contrib-htmlhint#2]
Hi,

Thanks for sharing your contribution. Now, tons of instructions as to how to install, configure, contribute... but where the hell is the **USAGE** part? Isn't that missing?

**Comment by mmaday** [comment]
I'm not totally sure what you mean.  Are you referring to the setup of the .htmlhintrc file?

**Comment by nmaxcom** [comment]
I think i'm being very clear. How one goes about **using** htmlhint within Sublime Text? What are the commands? What's the workflow?

**Comment by mmaday** [comment]
There are no commands.  This is a plugin that works within SublimeLinter 3.  I suggest you consult the documentation there if you are confused: http://www.sublimelinter.com/en/latest/about.html
