### ISSUE TITLE
Possibility to check HTML in *.php files

### ISSUE THREAD

**Issue by PixelT** [mmaday/SublimeLinter-contrib-htmlhint#3]
As in title - it will be nice to can check / lint the HTML markup inside the *.php files (or in PHP syntax)

**Comment by mmaday** [comment]
Sorry, HTMLHint currently only works on HTML and doesn't support any templates, etc.  Some have requested this feature, but the author has mentioned it's only intended for HTML: https://github.com/yaniswang/HTMLHint/issues/23.  

It'd be outside of the SublimeLinter workflow, but you could leverage something like https://github.com/kazu69/grunt-htmlhint-inline or https://github.com/kazu69/gulp-htmlhint-inline if you're using grunt/gulp.
