### ISSUE TITLE
Only checking on file save when background lint is on.

### ISSUE THREAD

**Issue by conor-byrne** [mmaday/SublimeLinter-contrib-htmlhint#5]
Hi there,

Firstly, thanks for making this plugin, it's much appreciated!

Anyhow, I'm having a slight problem where linting only occurs when the file is saved. SublimeLinter's lint mode is set to background and works just fine with pyflakes for my python scripts and csslint for my css files.

If you have any ideas, that'd be great. Cheers!

**Comment by mmaday** [comment]
Yes, this is a current limitation in htmlhint.  It does not accept input to stdin, so this plugin cannot perform linting until the file is saved.  I've requested this feature in htmlhint: https://github.com/yaniswang/HTMLHint/issues/97.  If it's ever implemented, it'd be quick fix to enable realtime linting.

**Comment by conor-byrne** [comment]
Ah great, thank you very much!
